helm:
  parameters:
  - name: nginx
    value: image=jacka12/nginx:6
    forcestring: false
  - name: nginx.image
    value: jacka12/nginx:6
    forcestring: false
  - name: image.name
    value: jacka12/nginx
    forcestring: true
  - name: image.tag
    value: "6"
    forcestring: true
