apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.service }} 
spec:
  selector: {{ include "common.labels" . | nindent 6 }}
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.port }}
      nodePort: 30090      
