apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.name }}
  labels: {{ include "common.labels" . | nindent 6 }}
spec:
  selector:
    matchLabels: {{ include "common.labels" . | nindent 8 }}
  #serviceName: {{ .Values.nginx.service }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels: {{ include "common.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Values.nginx.name }}
        {{- $v := $.Files.Get ".argocd-source-nginx.yaml" | fromYaml }}
        {{- $n := index $v.helm.parameters 0 }}
        {{- $m := index $v.helm.parameters 1 }}
        image: "{{ $n.value  }}:{{ $m.value}}"
        ports:
        - containerPort: {{ .Values.nginx.port }}
          name: {{ .Values.nginx.name }}
